#!/usr/bin/env node
/**
 * Exports academy/ as a standalone, deployable repository.
 *
 * The programme app lives here as a section of gobeyondadvisory.com, but it is
 * also a portfolio piece in its own right and deserves its own repository. This
 * writes that repository — app files, icon generator, CI, headers, licence and
 * a README written for the standalone context — without duplicating any content
 * in this tree. academy/ stays the single source of truth.
 *
 *   node scripts/export-academy.mjs [target-directory]
 *
 * Default target: ../ai-cloud-infrastructure-program
 *
 * Then, from the target directory:
 *   git init -b main && git add -A && git commit -m "Initial commit"
 *   git remote add origin git@github.com:<you>/ai-cloud-infrastructure-program.git
 *   git push -u origin main
 */
import { cpSync, mkdirSync, readFileSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const target = process.argv[2] || '../ai-cloud-infrastructure-program';
const NAME = 'ai-cloud-infrastructure-program';

if (existsSync(target)) {
  // Refuse to touch a directory that already holds work, but allow a re-export
  // over a tree this script produced.
  if (!existsSync(join(target, '.exported-by-export-academy'))) {
    console.error(
      `Refusing to write to ${target}: it exists and was not created by this script.\n` +
        'Pass a different target directory, or delete that one first.'
    );
    process.exit(1);
  }
  rmSync(target, { recursive: true, force: true });
}

const write = (rel, content) => {
  const path = join(target, rel);
  mkdirSync(join(path, '..'), { recursive: true });
  writeFileSync(path, content);
};

mkdirSync(target, { recursive: true });
write('.exported-by-export-academy', 'Generated by scripts/export-academy.mjs in gobeyondadvisory-site.\n');

// ── App files, verbatim except where the standalone context differs ─────────
for (const f of ['app.css', 'app.js', 'curriculum.js', 'sw.js']) {
  cpSync(join('academy', f), join(target, f));
}
cpSync('academy/icons', join(target, 'icons'), { recursive: true });
cpSync('LICENSE', join(target, 'LICENSE'));

// The copy inside gobeyondadvisory.com is noindex, because an operator's
// training tool has no business in an advisory firm's search results. The
// standalone repository is the opposite: it is portfolio evidence and should
// be findable.
const index = readFileSync('academy/index.html', 'utf8').replace(
  /^\s*<meta name="robots" content="noindex, nofollow"\/>\n/m,
  ''
);
if (index.includes('noindex')) {
  console.error('Expected to strip the noindex meta tag and did not. Aborting rather than exporting a noindex site.');
  process.exit(1);
}
write('index.html', index);

// At the root of its own domain the manifest identity is "/" rather than
// "/academy/". Everything else about it is already path-relative.
const manifest = JSON.parse(readFileSync('academy/manifest.webmanifest', 'utf8'));
manifest.id = '/';
write('manifest.webmanifest', JSON.stringify(manifest, null, 2) + '\n');

// The icon generator, with its output paths moved to the repository root.
const icons = readFileSync('scripts/build-academy-icons.mjs', 'utf8')
  .replace(/academy\/icons/g, 'icons')
  .replace('node scripts/build-academy-icons.mjs', 'npm run icons');
write('scripts/build-icons.mjs', icons);

// ── Project files ──────────────────────────────────────────────────────────
write(
  'package.json',
  JSON.stringify(
    {
      name: NAME,
      private: true,
      description:
        'A 24-week accelerated training programme: zero technical experience to employable entry-level Cloud, DevOps and AI Infrastructure Engineer.',
      license: 'MIT',
      type: 'module',
      engines: { node: '>=20' },
      scripts: {
        icons: 'node scripts/build-icons.mjs',
        check: 'node scripts/check.mjs',
        serve: 'npx --yes serve@14.2.4 --no-clipboard .',
        validate: 'npm run check',
      },
    },
    null,
    2
  ) + '\n'
);

write(
  '.gitignore',
  ['node_modules/', 'package-lock.json', '.netlify/', '.DS_Store', 'Thumbs.db', '.idea/', '.vscode/', '*.log', '.env', '.env.*', '.exported-by-export-academy', ''].join('\n')
);

write('.nvmrc', '22\n');

write(
  '.htmlvalidate.json',
  JSON.stringify(
    { root: true, extends: ['html-validate:recommended'], rules: { 'void-style': 'off', 'no-inline-style': 'off', 'no-raw-characters': 'off', 'long-title': 'off', 'attribute-boolean-style': 'off' } },
    null,
    2
  ) + '\n'
);

write(
  'netlify.toml',
  `# Netlify configuration for ${NAME}.
#
# A static progressive web app with no build step: the repository root is
# published as-is.

[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/scripts/*"
  to = "/index.html"
  status = 404
  force = true

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cross-Origin-Opener-Policy = "same-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    Content-Security-Policy = """\\
      default-src 'self'; \\
      base-uri 'none'; \\
      object-src 'none'; \\
      frame-ancestors 'none'; \\
      form-action 'self'; \\
      script-src 'self'; \\
      style-src 'self' https://fonts.googleapis.com; \\
      font-src 'self' https://fonts.gstatic.com; \\
      img-src 'self' data:; \\
      connect-src 'self'; \\
      manifest-src 'self'; \\
      worker-src 'self'; \\
      upgrade-insecure-requests"""

    # Nothing here is fingerprinted and the service worker manages its own
    # cache, so no file may be cached immutably.
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
`
);

// A small check script, so the repository has a real quality gate of its own.
write(
  'scripts/check.mjs',
  `#!/usr/bin/env node
/**
 * Structural checks for this repository. Zero dependencies, so it runs on a
 * clean clone. These encode the things that would actually break the app:
 * a curriculum that does not parse, a week missing its quiz, a skill reference
 * that points at nothing, an insecure reading link, or a file the service
 * worker precaches by name that is not on disk.
 */
import { readFileSync, existsSync } from 'node:fs';

const fail = [];
const check = (cond, msg) => { if (!cond) fail.push(msg); };

// The curriculum must parse and be internally consistent.
globalThis.window = {};
const src = readFileSync('curriculum.js', 'utf8');
new Function(src).call(globalThis);
const C = globalThis.window.CURRICULUM;

check(!!C, 'curriculum.js did not define window.CURRICULUM');
check(C.weeks.length === C.meta.weeks, \`expected \${C.meta.weeks} weeks, found \${C.weeks.length}\`);
C.weeks.forEach((w, i) => {
  check(w.n === i + 1, \`week \${i + 1} is numbered \${w.n}\`);
  check(w.quiz && w.quiz.length >= 5, \`week \${w.n} has fewer than 5 quiz questions\`);
  w.quiz.forEach((q, j) => {
    check(q.options.length >= 2, \`week \${w.n} question \${j + 1} has fewer than 2 options\`);
    check(q.answer >= 0 && q.answer < q.options.length, \`week \${w.n} question \${j + 1} answer index is out of range\`);
    check(!!q.explain, \`week \${w.n} question \${j + 1} has no explanation\`);
  });
  w.skills.forEach((id) => check(C.skills.some((s) => s.id === id), \`week \${w.n} references unknown skill "\${id}"\`));
  w.reading.forEach((r) => check(r.url.startsWith('https://'), \`week \${w.n} reading link is not https: \${r.url}\`));
  check(w.cost && w.cost.length, \`week \${w.n} has no cost note\`);
  check(w.security && w.security.length, \`week \${w.n} has no security note\`);
  check(!!w.deliverable && !!w.deliverable.repo, \`week \${w.n} has no GitHub deliverable\`);
});
C.lessons.forEach((l) => {
  check(l.quiz.length === 5, \`lesson \${l.id} does not have exactly 5 quiz questions\`);
  check(!!C.weeks.find((w) => w.n === l.week), \`lesson \${l.id} belongs to no week\`);
});
check(C.projects.length === 6, 'expected 6 portfolio projects');
check(C.gates.length === 8, 'expected 8 employment gates');

// Every file the service worker precaches must exist, or install fails and the
// app is not available offline at all.
const shell = [...readFileSync('sw.js', 'utf8').matchAll(/'\\.\\/([^']*)'/g)].map((m) => m[1]).filter(Boolean);
shell.forEach((f) => check(existsSync(f), \`sw.js precaches "\${f}", which is not on disk\`));

// No secrets, ever.
for (const f of ['index.html', 'app.js', 'curriculum.js', 'sw.js']) {
  const s = readFileSync(f, 'utf8');
  check(!/AKIA[0-9A-Z]{16}/.test(s), \`\${f} contains something shaped like an AWS access key\`);
  check(!/\\bgh[pousr]_[A-Za-z0-9]{20,}/.test(s), \`\${f} contains something shaped like a GitHub token\`);
}

if (fail.length) {
  console.error(\`\\u2716 \${fail.length} problem(s):\\n\`);
  for (const f of fail) console.error('  ' + f);
  process.exit(1);
}
console.log(\`\\u2714 checks passed \\u2014 \${C.weeks.length} weeks, \${C.lessons.length} written lessons, \${C.skills.length} skills, \${shell.length} precached files.\`);
`
);

write(
  '.github/workflows/ci.yml',
  `name: CI

on:
  push:
    branches: ['**']
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Curriculum and app checks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version-file: .nvmrc

      # Curriculum integrity, service-worker precache list, committed secrets.
      - run: node scripts/check.mjs

      # The icons are generated. If regenerating changes them, the committed
      # PNGs are stale.
      - run: node scripts/build-icons.mjs
      - run: git diff --exit-code -- icons/

  html:
    name: HTML validation
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version-file: .nvmrc
      - run: npx --yes html-validate@8.24.2 '*.html'
`
);

write('README.md', readmeText());
console.log(`Exported ${NAME} to ${target}`);
console.log('\nNext:');
console.log(`  cd ${target}`);
console.log('  npm run check');
console.log('  git init -b main && git add -A && git commit -m "Initial commit"');
console.log(`  git remote add origin https://github.com/<you>/${NAME}.git`);
console.log('  git push -u origin main');

function readmeText() {
  return `# AI Cloud Infrastructure Program

A 24-week accelerated training programme, delivered as an offline-first
progressive web app: **zero technical experience to employable entry-level
Cloud, DevOps and AI Infrastructure Engineer.**

## What this is

Not a reading list. A structured programme with the parts that actually produce
competence: daily lessons, laboratories you run yourself, quizzes that withhold
their answers until you attempt them, a skills matrix you have to be honest
with, an error log, spaced repetition on everything you got wrong, six
production-style portfolio projects, and eight employment-readiness gates.

| | |
| --- | --- |
| Duration | 24 weeks — Mon–Fri 90 minutes, Saturday 3-hour build, Sunday review |
| Phases | 6, from Linux and networking to production AI inference |
| Tracked skills | 84, across five competence levels |
| Portfolio projects | 6, each against a 17-point quality checklist |
| Gates | 8, with job applications starting at Gate 5 — not Week 24 |

### The six phases

1. **Weeks 1–4** — Computer, Linux and networking foundations
2. **Weeks 5–8** — Python, Bash, Git and software foundations
3. **Weeks 9–13** — Cloud computing, infrastructure as code and DevOps
4. **Weeks 14–17** — Docker, Kubernetes, reliability and observability
5. **Weeks 18–21** — AI, LLMs, RAG, agents and MCP
6. **Weeks 22–24** — Production AI infrastructure, portfolio and employment

### The six projects

| # | Project | Week | Cost |
| --- | --- | --- | --- |
| 1 | Linux and Networking Operations Laboratory | 4 | USD 0 |
| 2 | Automated Cloud Web Platform (AWS + Terraform + CI/CD) | 13 | ~USD 5–15 if torn down same day |
| 3 | Kubernetes Application Platform (Helm, Prometheus, Argo CD) | 17 | USD 0 locally |
| 4 | Beginner Enterprise RAG Assistant | 19 | USD 0 fully local |
| 5 | Secure Agent and MCP Assistant (LangGraph) | 21 | USD 0 fully local |
| 6 | AI Model Serving and Benchmark (vLLM) | 23 | Capped at USD 20 |

## What it refuses to do

- **It will not overstate you.** The programme trains junior-level competence.
  Nothing in it should ever appear on a CV as paid professional experience.
- **It will not show you an answer before you attempt it.** The correct option
  is never written into the page until you submit.
- **It will not let a mistake disappear.** A wrong answer is scheduled for
  spaced repetition at 1, 3, 7, 16 and 35 days.
- **It will not pretend cloud laboratories are free.** Every week carries a cost
  note in USD and every project carries teardown instructions. The most
  expensive habits — a forgotten NAT gateway, load balancer, EKS control plane
  or rented GPU — are called out where they occur.
- **It will not accept "it works".** Availability, latency percentiles, cost per
  request, cost per million tokens, retrieval recall — the programme requires a
  baseline, a change, and an honest report including results that got worse.

## Running it

No build step, no dependencies, no backend.

\`\`\`bash
npm run serve     # http://localhost:3000
npm run check     # curriculum integrity, precache list, secret scan
npm run icons     # regenerate icons/*.png
\`\`\`

Open it, install it from the browser's address bar, and it works offline —
including on a phone, on a train, with no signal.

## How it is built

| Path | Purpose |
| --- | --- |
| \`index.html\` | App shell. One page; every route is a URL hash |
| \`app.css\` | All styles. Tokens on \`:root\`; the dark theme redefines tokens only |
| \`app.js\` | Router, state, views, quiz engine, spaced repetition |
| \`curriculum.js\` | **All content**, as pure data |
| \`sw.js\` | Service worker. Precaches the shell and the whole curriculum |
| \`scripts/check.mjs\` | Curriculum integrity checks |
| \`scripts/build-icons.mjs\` | Writes the PNG icons directly — no image toolchain |

### Design decisions

- **Content is data, not markup.** \`curriculum.js\` holds every week, lesson,
  skill, project and gate as a plain object, so the curriculum can be reviewed
  and corrected independently of the app that renders it. CI checks that every
  week has a quiz, that every quiz answer index is in range, that every skill
  reference resolves, and that every reading link is https.
- **No backend and no accounts.** Progress lives in one versioned
  \`localStorage\` key. That is the honest trade: nothing about the learner
  leaves the device, but progress is per-device and per-browser — so Settings
  offers export and restore, and says so plainly rather than hiding it.
- **Offline is the default, not a feature.** The service worker precaches the
  shell and the curriculum on first visit. Only the official reading links need
  a network.
- **Icons are generated, not committed by hand.** \`scripts/build-icons.mjs\`
  writes valid PNGs using only Node's zlib and a CRC32 table. CI regenerates
  them and fails if the committed files differ.

### Known limitations

- Daily lessons are written out in full for Week 1. Later weeks derive a
  Monday-to-Friday plan from their concepts and laboratories; writing them out
  as you reach them is part of the programme.
- Progress does not sync between devices. Export and restore is manual, by
  design — adding sync would mean adding a backend and an account, and storing
  someone's learning record on a server.
- The app cannot verify that you actually did the work. Nothing can. The skills
  matrix is only as useful as your honesty with it.

## Licence

[MIT](LICENSE).
`;
}
